// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        int64            `json:"id"`
	Content   string           `json:"content"`
	UserID    int64            `json:"user_id"`
	Username  string           `json:"username"`
	PostID    int64            `json:"post_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Post struct {
	ID        int64            `json:"id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	UserID    int64            `json:"user_id"`
	Username  string           `json:"username"`
	TopicID   int64            `json:"topic_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Topic struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	UserID      int64            `json:"user_id"`
	Username    string           `json:"username"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        int64            `json:"id"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
