// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	ListTopics(ctx context.Context) ([]Topic, error)
}

var _ Querier = (*Queries)(nil)
