// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, id int64) (Comment, error)
	DeletePost(ctx context.Context, id int64) (Post, error)
	DeleteTopic(ctx context.Context, id int64) (Topic, error)
	FetchUser(ctx context.Context, username string) (User, error)
	ListComments(ctx context.Context, postID int64) ([]Comment, error)
	ListPosts(ctx context.Context, topicID int64) ([]Post, error)
	ListTopics(ctx context.Context) ([]Topic, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error)
}

var _ Querier = (*Queries)(nil)
